apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: devfile-sample-hno7
spec:
  replicas: 1
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/pmacik-testing/tkrw-pr712-0075-0042-tenant/tkrw-pr712-0075-0042-app/devfile-sample-hno7@sha256:fd75d0b35caaf00d6a49d8294af0ff5411adedf48e8c8592f6b0e4f20a4a3d5c
        name: my-nodejs
        resources: {}
status: {}
